---
- name: Update repositories
  apt: update_cache=true
  when: ansible_os_family == "Debian"

- name: Install useful stuff (Debian)
  apt: name={{ item }} state=present
  with_items:
    - htop
    - tmux
    - zip
    - unzip
    - git
    - zsh
    - vim
    - wget
    - curl
    - iptables-persistent
  when: ansible_os_family == "Debian"
  
- name: Install useful stuff (RedHat)
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - tmux
    - htop
    - zip
    - unzip
    - git
    - wget
    - vim
    - tar
    - zsh
    - curl
  when: ansible_os_family == "RedHat"

- name: Install Open VM Tools
  apt: name=open-vm-tools state=present
  when: (ansible_virtualization_type == "VMware" and ansible_os_family == "Debian")
- name: Install Open VM Tools (RedHat)
  yum: name=open-vm-tools state=present
  when: (ansible_virtualization_type == "VMware" and ansible_os_family == "RedHat")
