---
- name: Add webupd8team repository
  shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list

- name: Add webupd8team repository src
  shell: echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list

- name: Add repository keys
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886

- name: Update repositories
  apt: update_cache=yes

- name: Install oracle-java8-installer
  apt: name=oracle-java8-installer state=present
